version : '3.7'

services:
  mysql:
    image : mysql:8.0.32
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: opentutorials
      MYSQL_USER: nodejs
      MYSQL_PASSWORD: 123456

  studynode: 
    depends_on:
      - mysql
    image : ghcr.io/ramen4598/studynode:3.0-multiarch
    volumes :
      - ./src/:/app/src/
    ports :
      - "3000:3000"
    restart : always
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: opentutorials
      MYSQL_USER: nodejs
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
