#docker run -it --name studynode -p 3000:3000 -v ~/Desktop/Study_nodeJS/:/app/  studynode:1.0
version : '1.1'

services:
  studynode: 
    image : ghcr.io/ramen4598/studynode:1.1
    volumes :
      - ./studynode:/app/
    ports :
      - "3000:3000"
    restart : always
